# SPDX-License-Identifier: BSD-3-Clause
# Copyright(c) 2022-23 Intel Corporation

---
# check WAITPKG availability
- name: Check if WAITPKG is supported on the platform
  command: grep -q 'waitpkg' '/proc/cpuinfo'
  register: waitpkg_available
  changed_when: false
  failed_when: waitpkg_available.rc != 0
  check_mode: no

- debug:
    msg: "{{ waitpkg_available }}"
  when: ansible_check_mode
