# SPDX-License-Identifier: BSD-3-Clause
# Copyright(c) 2020-21 Intel Corporation

---
# defaults file for lowlatency-platform-provisioning
state: present

# CommsPowerManagement repo details
commspower_repo: https://github.com/intel/CommsPowerManagement.git
commspower_repo_version: master

# Directory where CommsPowerManagement repo should be cloned.
commspower_dir: commspower_repo

# MSR tools for SUSE
msrtools_repo: https://github.com/intel/msr-tools.git
msrtools_version: msr-tools-1.3
msrtools_dir: msrtools_repo

# list of latency measuring cores.
cores:
  - 20
  - 21
  - 22

# List of example boot params for low latency system,
# out of which tsc, isolcpus, rcu_nocbs, nohz_full are
# important parameters, rest of the parameters should be
# adjusted as per the need, so understand impact of them
# before using.
# Any existing grub boot command will be replaced with this.

grub_cmdline_add_args:
  - ro
  - rhgb
  - quiet
  - hugepages=4
  - hugepagesz=1G
  - intel_iommu=on
  - iommu=pt
  - mce=off
  - nosoftlockup
  - nmi_watchdog=0
  - hpet=disable
  - tsc=reliable
  - isolcpus=20-22
  - rcu_nocbs=20-22
  - nohz_full=20-22

# grub file path
grub_cmdline_default: /etc/default/grub

# Paths to various boot config files
efi_boot_config: /boot/efi/EFI
grub_boot_config: /boot/grub
grub2_boot_config: /boot/grub2
grubmkcfg: /usr/sbin/grub*-mkconfig

# pstate driver path
pstate_sysfs_path: /sys/devices/system/cpu/cpufreq/policy0/scaling_driver

# cstate driver path
cstate_sysfs_path: /sys/devices/system/cpu/cpuidle/current_driver


# From kernel >= 5.6, sysfs path can be used to set the uncore
# frequency.
# ls /sys/devices/system/cpu/intel_uncore_frequency/package_00_die_00/
# initial_max_freq_khz initial_min_freq_khz max_freq_khz min_freq_khz
uncore_sysfs_path: /sys/devices/system/cpu/intel_uncore_frequency
uncore_maxfreq_file: max_freq_khz
uncore_minfreq_file: min_freq_khz

# uncore p1 frequency (in Khz) to set using sysfs entry
uncore_freq_clx_khz: 1800000
uncore_freq_icx_khz: 1400000

# uncore frequency (in Hex) to set using MSR.
uncore_freq_clx: 0x1212
uncore_freq_icx: 0x0e0e

# Cascade Lake
clx_type: Intel(R) Xeon(R) Gold 6230N CPU @ 2.30GHz

# provisioning status files will be created under this path.
prov_status_dir: /var/run/intel/platform-provisioning

cpu_path: /sys/devices/system/cpu
